name: Node.js CI

inputs:
  ACTOR:
    required: true
  CR_PAT:
    required: true
  IMAGE_TAG:
    required: true

runs:
  using: "composite"
  steps:
  - name: Use Node.js 16.x
    uses: actions/setup-node@v3
    with:
      node-version: 16.x
      cache: 'npm'
  - run: npm ci
  - run: npm run test
  - run: npm run build --if-present
  - run: rm -rf node_modules
  - run: npm i --only=prod
  
  - name: Login to GitHub Container Registry
    uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ inputs.ACTOR }}
      password: ${{ inputs.CR_PAT }}
  - run: docker build . --file Dockerfile --tag ${{ inputs.IMAGE_TAG }}
  - run: docker push ${{ inputs.IMAGE_TAG }}

outputs:
  image-tag:
    description: "Image Tag"
    value: ${{ inputs.IMAGE_TAG }}
