name: prepare-env

inputs:
  CR_PAT:
    required: true
  PUBLIC_URL:
    required: false
    default: "1"
  REACT_APP_CDN_URL:
    required: false
    default: "1"
  REACT_APP_API_URL:
    required: false
    default: "1"
  REACT_APP_ZOOM_URI_LOGIN:
    required: false
    default: "1"
  REACT_APP_APPLICATION_DNS:
    required: false
    default: "1"
  REACT_APP_API_TOKEN:
    required: false
    default: "1"
  ST_MONGO_USERNAME:
    required: false
    default: "1"

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      repository: easytecs/eks-deployment
      token: ${{ inputs.CR_PAT }}
  - run: mkdir -p ./deployment
    shell: bash
  - run: python ./STBuild/convert-env-front.py PUBLIC_URL=${{ inputs.PUBLIC_URL }} REACT_APP_API_URL=${{ inputs.REACT_APP_API_URL }} REACT_APP_ZOOM_URI_LOGIN=${{ inputs.REACT_APP_ZOOM_URI_LOGIN }} REACT_APP_APPLICATION_DNS=${{ inputs.REACT_APP_APPLICATION_DNS }} REACT_APP_CDN_URL=${{ inputs.REACT_APP_CDN_URL }} REACT_APP_API_TOKEN="${{ inputs.REACT_APP_API_TOKEN }}"
    shell: bash
  - run: cat ./deployment/.env.production.local
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: deployment-env-front
      path: ./deployment
