name: prepare-env

inputs:
  APPLICATION_NAME:
    required: true
  APPLICATION_PORT:
    required: true
  CR_PAT:
    required: true
  REPOSITORY:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      repository: ${{ inputs.REPOSITORY }}
      token: ${{ inputs.CR_PAT }}

  - uses: actions/checkout@v2
    with:
      repository: easytecs/eks-deployment
      token: ${{ inputs.CR_PAT }}
  - run: ls -la
    shell: bash
  - run: mkdir -p ./deployment
    shell: bash
  - run: python ./STBuild/convert-ingress.py APPLICATION_NAME=${{ inputs.APPLICATION_NAME }} APPLICATION_PORT=${{ inputs.APPLICATION_PORT }}
    shell: bash
  - run: cat ./deployment/ingress.yaml
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: deployment-ingress
      path: ./deployment
