name: prepare-env

inputs:
  secrets: 
    required: false
  config-map:
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: python ./env/convert-env.py
    shell: bash
  - run: cat ./env/secrets.yaml
    shell: bash
  # - run: echo "${{ inputs.config-map-file }}" > ./env/secrets.yaml
    # shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: env
      path: env/
