name: prepare-env

inputs:
  APPLICATION_NAME:
    required: true
  ST_MONGO_USERNAME:
    required: false
  ST_MONGO_PASSWORD:
    required: false
  ST_MONGO_HOST:
    required: false
  ST_MONGO_DB_DATABASE:
    required: false
  ST_APPLICATION_PORT:
    required: false
  ST_API_GATEWAY_URL:
    required: false
  ST_ELASTICSEARCH_NODE:
    required: false
  ST_ELASTICSEARCH_USER:
    required: false
  ST_ELASTICSEARCH_PWD:
    required: false
  ST_HASH_SALT:
    required: false
  ST_EMAIL_HOST_SMTP:
    required: false 
  ST_EMAIL_USERNAME:
    required: false
  ST_EMAIL_PASSWORD:
    required: false
  ST_ZOOM_HOST:
    required: false
  ST_CALENDAR_HOST:
    required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: python ./env/convert-env.py
    shell: bash
  - run: ls -la
    shell: bash
  - run: ls -la ./env
    shell: bash
  - run: cat ./env/secrets.yaml
    shell: bash
  # - run: echo "${{ inputs.config-map-file }}" > ./env/secrets.yaml
    # shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: env
      path: env/
