name: prepare-env
env:
   SECRETS_FILE: '
apiVersion: v1
kind: Secret
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: { ... }
  name: secrets
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque
data:'

inputs:
  secrets-file: 
    required: true
  config-map-file:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: mkdir -p env/
    shell: bash
  - run: cat "${{ env.SECRETS_FILE }}" >> ./env/secrets-tmp.yaml
    shell: bash
  - run: cat "${{ inputs.secrets-file }}" >> ./env/secrets.yaml
    shell: bash
  - run: cat "${{ inputs.config-map-file }}" >> ./env/secrets.yaml
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: env
      path: env/
