name: prepare-env

# inputs:
#   MONGO_USERNAME:
#       required: false
#   MONGO_PASSWORD:
#       required: false
#   MONGO_HOST:
#       required: false
#   MONGO_DB_DATABASE:
#       required: false
#   APPLICATION_PORT:
#       required: false
#   API_GATEWAY_URL:
#       required: false
#   ELASTICSEARCH_NODE:
#       required: false
#   ELASTICSEARCH_USER:
#       required: false
#   ELASTICSEARCH_PWD:
#       required: false
#   HASH_SALT:
#       required: false
#   EMAIL_HOST_SMTP:
#       required: false 
#   EMAIL_USERNAME:
#       required: false
#   EMAIL_PASSWORD:
#       required: false
#   ZOOM_HOST:
#       required: false
#   CALENDAR_HOST:
#       required: false

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: python ./env/convert-env.py ${{ secrets }}
    shell: bash
  - run: ls -la
    shell: bash
  - run: ls -la ./env
    shell: bash
  - run: cat ./env/secrets.yaml
    shell: bash
  # - run: echo "${{ inputs.config-map-file }}" > ./env/secrets.yaml
    # shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: env
      path: env/
