name: prepare-env

inputs:
  APPLICATION_NAME:
    required: true
    default: 1
  ST_MONGO_USERNAME:
    required: false
    default: 1
  ST_MONGO_PASSWORD:
    required: false
    default: 1
  ST_MONGO_HOST:
    required: false
    default: 1
  ST_MONGO_DB_DATABASE:
    required: false
    default: 1
  ST_APPLICATION_PORT:
    required: false
    default: 1
  ST_API_GATEWAY_URL:
    required: false
    default: 1
  ST_ELASTICSEARCH_NODE:
    required: false
    default: 1
  ST_ELASTICSEARCH_USER:
    required: false
    default: 1
  ST_ELASTICSEARCH_PWD:
    required: false
    default: 1
  ST_HASH_SALT:
    required: false
    default: 1
  ST_EMAIL_HOST_SMTP:
    required: false 
    default: 1
  ST_EMAIL_USERNAME:
    required: false
    default: 1
  ST_EMAIL_PASSWORD:
    required: false
    default: 1
  ST_ZOOM_HOST:
    required: false
    default: 1
  ST_CALENDAR_HOST:
    required: false
    default: 1

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: python ./env/convert-env.py APPLICATION_NAME=${{ input.APPLICATION_NAME }} ST_MONGO_USERNAME=${{ input.ST_MONGO_USERNAME }} ST_MONGO_PASSWORD=${{ input.ST_MONGO_PASSWORD }} ST_MONGO_HOST=${{ input.ST_MONGO_HOST }} ST_MONGO_DB_DATABASE=${{ input.ST_MONGO_DB_DATABASE }} ST_APPLICATION_PORT=${{ input.ST_APPLICATION_PORT }} ST_API_GATEWAY_URL=${{ input.ST_API_GATEWAY_URL }} ST_ELASTICSEARCH_NODE=${{ input.ST_ELASTICSEARCH_NODE }} ST_ELASTICSEARCH_USER=${{ input.ST_ELASTICSEARCH_USER }} ST_ELASTICSEARCH_PWD=${{ input.ST_ELASTICSEARCH_PWD }} ST_HASH_SALT=${{ input.ST_HASH_SALT }} ST_EMAIL_HOST_SMTP=${{ input.ST_EMAIL_HOST_SMTP }} ST_EMAIL_USERNAME=${{ input.ST_EMAIL_USERNAME }} ST_EMAIL_PASSWORD=${{ input.ST_EMAIL_PASSWORD }} ST_ZOOM_HOST=${{ input.ST_ZOOM_HOST }} ST_CALENDAR_HOST=${{ input.ST_CALENDAR_HOST }}     shell: bash
  - run: ls -la
    shell: bash
  - run: ls -la ./env
    shell: bash
  - run: cat ./env/secrets.yaml
    shell: bash
  # - run: echo "${{ inputs.config-map-file }}" > ./env/secrets.yaml
    # shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: env
      path: env/
