name: Node.js CI

inputs:
  ACTOR:
    required: true
  CR_PAT:
    required: true
  IMAGE_TAG:
    required: true
  RESPOSITORY:
    required: true

runs:
  using: "composite"
  steps:
  - name: Clone Project
    uses: actions/checkout@v2
    with:
      repository: easytecs/eks-deployment
      token: ${{ inputs.CR_PAT }}

  - name: Build the Docker image
  - run: docker build . --file Dockerfile --tag ${{ inputs.IMAGE_TAG }}
    shell: bash

  - uses: docker/login-action@v2
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ inputs.CR_PAT }}

  - name: Push the Docker image
  - run: docker push ${{ inputs.IMAGE_TAG }}
    shell: bash
    with:
      repository:  ${{ inputs.RESPOSITORY }}
      token: ${{ inputs.CR_PAT }}
      
outputs:
  image-tag:
    description: "Image Tag"
    value: ${{ inputs.IMAGE_TAG }}
