name: prepare-application

inputs:
  APPLICATION_NAME:
    required: true
  DEPLOYMENT_IMAGE:
    required: true
  APPLICATION_PORT:
    required: true
  APPLICATION_ARGS:
    required: false
  APPLICATION_PATH_HEALTH:
    required: false


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: mkdir -p ./deployment
    shell: bash

  - run: python ./STBuild/create-service-deployment.py ${{ inputs.APPLICATION_NAME }} ${{ inputs.DEPLOYMENT_IMAGE }} ${{ inputs.APPLICATION_PORT }} ${{ inputs.NBL_NAME }} ${{ inputs.APPLICATION_PATH_HEALTH }} ${{ inputs.APPLICATION_ARGS }}
    shell: bash

  - run: cat ./deployment/application.yaml
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: deployment-application
      path: ./deployment
