name: prepare-application

inputs:
  APPLICATION_NAME:
    required: true
  DEPLOYMENT_IMAGE:
    required: true
  APPLICATION_PORT:
    required: true
  APPLICATION_ARGS:
    required: false
  APPLICATION_PATH_HEALTH:
    required: false


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      repository: easytecs/eks-deployment
      token: ${{ inputs.CR_PAT }}

  - run: mkdir -p ./deployment
    shell: bash

  - run: python ./STBuild/create-service-deployment.py APPLICATION_NAME="${{ inputs.APPLICATION_NAME }}" DEPLOYMENT_IMAGE="${{ inputs.DEPLOYMENT_IMAGE }}" APPLICATION_PORT="${{ inputs.APPLICATION_PORT }}" NBL_NAME="${{ inputs.NBL_NAME }}" APPLICATION_PATH_HEALTH="${{ inputs.APPLICATION_PATH_HEALTH }}" APPLICATION_ARGS="${{ inputs.APPLICATION_ARGS }}"
    shell: bash

  - run: cat ./deployment/application.yaml
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: deployment-application
      path: ./deployment
