name: Node.js CI

inputs:
  REPOSITORY:
    required: true
  IMAGE_TAG:
    required: true

runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
  - uses: actions/checkout@v2
  - run: mkdir -p ./release-version
    shell: bash
  - run: cat ${{ inputs.IMAGE_TAG }} ./release-version/release.txt
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: ${{ inputs.REPOSITORY }}
      path: ./release-version