name: prepare-application

inputs:
  APPLICATION_NAME:
    required: true
  DEPLOYMENT_IMAGE:
    required: true
  APPLICATION_PORT:
    required: true
  SERVICE_NAMESPACE:
    required: false
    default: st-service
  NBL_NAME:
    required: false
  APPLICATION_ARGS:
    required: false
  APPLICATION_PATH_HEALTH:
    required: false
    default: /health
  APPLICATION_INITIAL_DELAY:
    required: false
    default: 15


runs:
  using: "composite"
  steps:
  - uses: actions/checkout@v2
    with:
      repository: easytecs/eks-deployment
      token: ${{ inputs.CR_PAT }}

  - run: mkdir -p ./deployment
    shell: bash
  - run: python ./STBuild/create-application-deployment.py APPLICATION_NAME="${{ inputs.APPLICATION_NAME }}" APPLICATION_INITIAL_DELAY=${{ inputs.APPLICATION_INITIAL_DELAY }} SERVICE_NAMESPACE="${{ inputs.SERVICE_NAMESPACE }}" DEPLOYMENT_IMAGE="${{ inputs.DEPLOYMENT_IMAGE }}" APPLICATION_PORT="${{ inputs.APPLICATION_PORT }}" NBL_NAME="${{ inputs.NBL_NAME }}" APPLICATION_PATH_HEALTH="${{ inputs.APPLICATION_PATH_HEALTH }}"
    shell: bash

  - run: cat ./deployment/application.yaml
    shell: bash

  - uses: actions/upload-artifact@v3
    with:
      name: deployment-application
      path: ./deployment
