name: aws-depolyment

inputs:
  AWS_REGION:
    required: true
  EKS_CLUSTER_NAME:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  DO_API_PRIVATE_KEY:
    required: true
  SERVICE_RELEASE_NAME:
    required: true
  SERVICE_NAMESPACE:
    required: true
  SERVICE_HEML_VALUES:
    required: false
  SERVICE_HEML_NAME:
    required: true
  SERVICE_HELM_REPO:
    required: true
  RESPOSITORY:
    required: true
  CR_PAT:
    required: true

  SERVICE_HELM_CRD:
    required: false
    default: false

runs:
  using: "composite"
  steps:
            
    - name: Configure AWS credentials and EKS
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DO_API_PRIVATE_KEY }}
    - name: Deployment in kubernets
      run: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

          kubectl get namespace | grep -q "^${{ inputs.SERVICE_NAMESPACE }} " || kubectl create namespace ${{ inputs.SERVICE_NAMESPACE }}
          
          ${{ inputs.SERVICE_HELM_CRD }} && kubectl create -f ${{ inputs.SERVICE_HELM_CRD }} || echo "NO CREATE SERVICE_HELM_CRD" 

          helm repo add ${{ inputs.SERVICE_HELM_REPO }}
          helm repo update
          helm upgrade -i  ${{ inputs.SERVICE_HEML_NAME }} ${{ inputs.SERVICE_RELEASE_NAME }}  --namespace=${{ inputs.SERVICE_NAMESPACE }} ${{ inputs.SERVICE_HEML_VALUES }}