name: aws-depolyment

inputs:
  AWS_REGION:
    required: true
  EKS_CLUSTER_NAME:
    required: true
  AWS_ACCESS_KEY_ID:
    required: true
  AWS_SECRET_ACCESS_KEY:
    required: true
  SERVICE_RELEASE_NAME:
    required: true
  SERVICE_NAMESPACE:
    required: true
  SERVICE_HEML_VALUES:
    required: false
  SERVICE_HEML_NAME:
    required: true
  SERVICE_HELM_REPO:
    required: true

runs:
  using: "composite"
  steps:
    - name: Configure AWS credentials and EKS
      uses: safe2008/eks-actions@v0.0.4
      env:
        aws_access_key_id: ${{ inputs.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ inputs.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ inputs.AWS_REGION }}
        cluster_name: ${{ inputs.EKS_CLUSTER_NAME }}
      with:
        args: |
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3
          chmod 700 get_helm.sh
          /get_helm.sh
          helm repo add ${{ inputs.SERVICE_HELM_REPO }}
          helm repo update
          helm upgrade -i  ${{ inputs.SERVICE_HEML_NAME }} ${{ inputs.SERVICE_RELEASE_NAME }}  --namespace=${{ inputs.SERVICE_NAMESPACE }} ${{ inputs.SERVICE_HEML_VALUES }}