name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./prepare-env
        with:
          secrets-file: "hello"
          config-map-file: "world"
