name: Node.js CI

on:
  push:
    branches: [ develop ]

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
        
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run test
    - run: npm run build --if-present
    - run: rm -rf node_modules
    - run: npm i --only=prod
    
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CR_PAT }}
    - run: docker build . --file Dockerfile --tag ghcr.io/easytecs/application-customer:${GITHUB_SHA}
    - run: docker push ghcr.io/easytecs/application-customer:${GITHUB_SHA}
    - run: echo "ghcr.io/easytecs/application-customer:${GITHUB_SHA}"
