name: Run Service Using Helm

on:
  workflow_call:
    inputs:
      AWS_REGION:
        default: "us-east-1" 
        type: string
      EKS_CLUSTER_NAME:
        default: "eks-dev" 
        type: string

      APPLICATION_NAME:
        required: true
        type: string
      DEPLOYMENT_IMAGE:
        required: true
        type: string
      APPLICATION_PORT: 
        required: true
        type: string
     
      REPOSITORY:
        required: true
        type: string
      
      APPLICATION_ARGS:
        required: false
        type: string
        default: ""
      APPLICATION_PATH_HEALTH:
        required: false
        type: string
        default: "/heath"

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CR_PAT:
        required: true
      
jobs:     
  pre-env:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-env@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          ST_MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          ST_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          ST_MONGO_HOST: ${{ secrets.MONGO_HOST }}
          ST_MONGO_DB_DATABASE: ${{ secrets.MONGO_DB_DATABASE }}
          ST_APPLICATION_PORT: ${{ secrets.APPLICATION_PORT }}
          ST_API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
          ST_ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}
          ST_ELASTICSEARCH_USER: ${{ secrets.ELASTICSEARCH_USER }}
          ST_ELASTICSEARCH_PWD: ${{ secrets.ELASTICSEARCH_PWD }}
          ST_HASH_SALT: ${{ secrets.HASH_SALT }}
          ST_EMAIL_HOST_SMTP: ${{ secrets.EMAIL_HOST_SMTP }}
          ST_EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          ST_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ST_ZOOM_HOST: ${{ secrets.ZOOM_HOST }}
          ST_CALENDAR_HOST: ${{ secrets.CALENDAR_HOST }}
          CR_PAT: ${{ secrets.CR_PAT }}

  pre-application:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-service@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          APPLICATION_PORT: ${{ inputs.APPLICATION_PORT }}
          DEPLOYMENT_IMAGE: ${{ inputs.DEPLOYMENT_IMAGE }}
          REPOSITORY: ${{ inputs.REPOSITORY }}
          APPLICATION_ARGS: ${{ inputs.APPLICATION_ARGS }}
          CR_PAT: ${{ secrets.CR_PAT }}
          APPLICATION_PATH_HEALTH: ${{ inputs.APPLICATION_PATH_HEALTH }}

  build-node-image:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/build-service-image@main
        with:
          ACTOR: ${{ github.actor }}
          CR_PAT: ${{ secrets.CR_PAT }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          REPOSITORY: ${{ inputs.REPOSITORY }}

  aws-depolyment:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/aws-depolyment@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ inputs.EKS_CLUSTER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    needs: [pre-env, pre-application, build-node-image]

          
