name: Run NodeJs Deploy

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      DEPLOYMENT_IMAGE:
        required: true
        type: string
      APPLICATION_PORT: 
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      
      NBL_NAME: 
        default: "nbl-dev" 
        type: string
      AWS_REGION:
        default: "us-east-1" 
        type: string
      EKS_CLUSTER_NAME:
        default: "eks-dev" 
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CR_PAT:
        required: true

jobs:     
  pre-env:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-env-front@main
        with:
          PUBLIC_URL: ${{ secrets.MONGO_USERNAME }}
          REACT_APP_API_URL: ${{ secrets.MONGO_PASSWORD }}
          REACT_APP_ZOOM_URI_LOGIN: ${{ secrets.MONGO_HOST }}
          REACT_APP_APPLICATION_DNS: ${{ secrets.MONGO_DB_DATABASE }}
          
          CR_PAT: ${{ secrets.CR_PAT }}

  pre-application:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-application@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-frontend
          DEPLOYMENT_IMAGE: ${{ inputs.DEPLOYMENT_IMAGE }}
          APPLICATION_PORT: ${{ inputs.APPLICATION_PORT }}
          NBL_NAME: ${{ inputs.NBL_NAME }}
          CR_PAT: ${{ secrets.CR_PAT }}

  build-node-image:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/build-front-image@main
        with:
          ACTOR: ${{ github.actor }}
          CR_PAT: ${{ secrets.CR_PAT }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          REPOSITORY: ${{ inputs.REPOSITORY }}
    needs: [pre-env]

  aws-depolyment:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/aws-depolyment@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ inputs.EKS_CLUSTER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_INGRESS: 1
          SERVICE_NAMESPACE: st-application
    needs: [pre-env, pre-application, build-node-image]

  after-build:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/after-build@main
        with:
          REPOSITORY: ${{ inputs.APPLICATION_NAME }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          CR_PAT: ${{ secrets.CR_PAT }}
    needs: [pre-env, pre-application, pre-ingress]
