name: Run NodeJs Deploy

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      DEPLOYMENT_IMAGE:
        required: true
        type: string
      APPLICATION_PORT: 
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
        
      NAME_ENV_JSON:
        required: true
        type: string
      
      NBL_NAME: 
        default: "nbl-platform" 
        type: string
      AWS_REGION:
        default: "us-east-1" 
        type: string
      EKS_CLUSTER_NAME:
        default: "eks-platform" 
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DIGITALOCEAN_ACCESS_TOKEN:
        required: true
      CR_PAT:
        required: true

jobs:     
  pre-env:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-env-v2@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-frontend
          ENV_JSON: ${{ secrets[format('{0}', inputs.NAME_ENV_JSON)] }}
          CR_PAT: ${{ secrets.CR_PAT }}


  pre-front-env:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-env-front-v2@main
        with:
          ENV_JSON: ${{ secrets[format('{0}', inputs.NAME_ENV_JSON)] }}
          CR_PAT: ${{ secrets.CR_PAT }}

  pre-application:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-application@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-frontend
          APPLICATION_PATH_HEALTH: /
          APPLICATION_INITIAL_DELAY: 60
          DEPLOYMENT_IMAGE: ${{ inputs.DEPLOYMENT_IMAGE }}
          APPLICATION_PORT: ${{ inputs.APPLICATION_PORT }}
          NBL_NAME: ${{ inputs.NBL_NAME }}
          CR_PAT: ${{ secrets.CR_PAT }}

  build-node-image:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/digital-ocean-build-front-image@main
        with:
          ACTOR: ${{ github.actor }}
          CR_PAT: ${{ secrets.CR_PAT }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          REPOSITORY: ${{ inputs.REPOSITORY }}
          DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
    needs: [pre-env, pre-front-env]

  after-build:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/after-build@main
        with:
          REPOSITORY: ${{ inputs.APPLICATION_NAME }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          CR_PAT: ${{ secrets.CR_PAT }}
    needs: [pre-env, pre-front-env, pre-application]
