name: Run Service Using Helm

on:
  workflow_call:
    inputs:
      AWS_REGION:
        default: "us-east-1" 
        type: string
      EKS_CLUSTER_NAME:
        default: "eks-platform" 
        type: string
      SERVICE_RELEASE_NAME:
        required: true
        type: string
      SERVICE_NAMESPACE:
        required: true
        type: string
      SERVICE_HEML_NAME:
        required: true
        type: string
      SERVICE_HELM_REPO:
        required: true
        type: string
      SERVICE_HEML_VALUES:
        required: false
        type: string
      SERVICE_HELM_CRD:
        required: false
        type: string
      RESPOSITORY:
        required: false
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DO_API_PRIVATE_KEY:
        required: true

jobs:     

  aws-depolyment:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/digital-ocean-connect@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ inputs.EKS_CLUSTER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SERVICE_NAMESPACE: ${{ inputs.SERVICE_NAMESPACE }}
          SERVICE_HEML_VALUES: ${{ inputs.SERVICE_HEML_VALUES }}
          SERVICE_RELEASE_NAME: ${{ inputs.SERVICE_RELEASE_NAME }}
          SERVICE_HEML_NAME: ${{ inputs.SERVICE_HEML_NAME }}
          SERVICE_HELM_REPO: ${{ inputs.SERVICE_HELM_REPO }}
          SERVICE_HELM_CRD: ${{ inputs.SERVICE_HELM_CRD }}
          RESPOSITORY: ${{ inputs.RESPOSITORY }}
          CR_PAT: ${{ secrets.CR_PAT }}
          DO_API_PRIVATE_KEY: ${{ secrets.DO_API_PRIVATE_KEY }}

          
