name: Run NodeJs Deploy

on:
  workflow_call:
    inputs:
      APPLICATION_NAME:
        required: true
        type: string
      DEPLOYMENT_IMAGE:
        required: true
        type: string
      APPLICATION_PORT: 
        required: true
        type: string
      REPOSITORY:
        required: true
        type: string
      
      NBL_NAME: 
        default: "nbl-dev" 
        type: string
      AWS_REGION:
        default: "us-east-1" 
        type: string
      EKS_CLUSTER_NAME:
        default: "eks-dev" 
        type: string

      ST_MONGO_USERNAME:
        required: false
        default: "1"
        type: string
      ST_MONGO_PASSWORD:
        required: false
        default: "1"
        type: string
      ST_MONGO_HOST:
        required: false
        default: "1"
        type: string
      ST_MONGO_DB_DATABASE:
        required: false
        default: "1"
        type: string
      ST_APPLICATION_PORT:
        required: false
        default: "1"
        type: string
      ST_API_GATEWAY_URL:
        required: false
        default: "1"
        type: string
      ST_ELASTICSEARCH_NODE:
        required: false
        default: "1"
        type: string
      ST_ELASTICSEARCH_USER:
        required: false
        default: "1"
        type: string
      ST_ELASTICSEARCH_PWD:
        required: false
        default: "1"
        type: string
      ST_HASH_SALT:
        required: false
        default: "1"
        type: string
      ST_EMAIL_HOST_SMTP:
        required: false 
        default: "1"
        type: string
      ST_EMAIL_USERNAME:
        required: false
        default: "1"
        type: string
      ST_EMAIL_PASSWORD:
        required: false
        default: "1"
        type: string
      ST_ZOOM_HOST:
        required: false
        default: "1"
        type: string
      ST_CALENDAR_HOST:
        required: false
        default: "1"
        type: string
        
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      CR_PAT:
        required: true

jobs:     
  pre-env:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-env@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-application
          ST_MONGO_USERNAME: ${{ secrets.MONGO_USERNAME }}
          ST_MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          ST_MONGO_HOST: ${{ secrets.MONGO_HOST }}
          ST_MONGO_DB_DATABASE: ${{ secrets.MONGO_DB_DATABASE }}
          ST_APPLICATION_PORT: ${{ secrets.APPLICATION_PORT }}
          ST_API_GATEWAY_URL: ${{ secrets.API_GATEWAY_URL }}
          ST_ELASTICSEARCH_NODE: ${{ secrets.ELASTICSEARCH_NODE }}
          ST_ELASTICSEARCH_USER: ${{ secrets.ELASTICSEARCH_USER }}
          ST_ELASTICSEARCH_PWD: ${{ secrets.ELASTICSEARCH_PWD }}
          ST_HASH_SALT: ${{ secrets.HASH_SALT }}
          ST_EMAIL_HOST_SMTP: ${{ secrets.EMAIL_HOST_SMTP }}
          ST_EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
          ST_EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          ST_ZOOM_HOST: ${{ secrets.ZOOM_HOST }}
          ST_API_URL_QUEUE_EMAIL: ${{ secrets.API_URL_QUEUE_EMAIL }}
          ST_API_URL_SEARCH: ${{ secrets.API_URL_SEARCH }}
          ST_API_URL_CALENDAR: ${{ secrets.API_URL_CALENDAR }}
          ST_API_URL_CUSTOMER: ${{ secrets.API_URL_CUSTOMER }}
          ST_API_URL_QUEUE_MEET: ${{ secrets.API_URL_QUEUE_MEET }}
          CR_PAT: ${{ secrets.CR_PAT }}

  pre-ingress:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-ingress@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-application
          APPLICATION_PORT: ${{ inputs.APPLICATION_PORT }}
          REPOSITORY: ${{ inputs.REPOSITORY }}
          CR_PAT: ${{ secrets.CR_PAT }}

  pre-application:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/prepare-application@main
        with:
          APPLICATION_NAME: ${{ inputs.APPLICATION_NAME }}
          SERVICE_NAMESPACE: st-application
          DEPLOYMENT_IMAGE: ${{ inputs.DEPLOYMENT_IMAGE }}
          APPLICATION_PORT: ${{ inputs.APPLICATION_PORT }}
          NBL_NAME: ${{ inputs.NBL_NAME }}
          CR_PAT: ${{ secrets.CR_PAT }}

  build-node-image:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/build-node-image@main
        with:
          ACTOR: ${{ github.actor }}
          CR_PAT: ${{ secrets.CR_PAT }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          REPOSITORY: ${{ inputs.REPOSITORY }}

  aws-depolyment:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/aws-depolyment@main
        with:
          AWS_REGION: ${{ inputs.AWS_REGION }}
          EKS_CLUSTER_NAME: ${{ inputs.EKS_CLUSTER_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          DEPLOYMENT_INGRESS: 1
          SERVICE_NAMESPACE: st-application
          CR_PAT: ${{ secrets.CR_PAT }}
    needs: [pre-env, pre-application, pre-ingress, build-node-image]

  after-build:
    runs-on: ubuntu-latest
    steps:
      - uses: easytecs/eks-deployment/after-build@main
        with:
          REPOSITORY: ${{ inputs.APPLICATION_NAME }}
          IMAGE_TAG: ${{ inputs.DEPLOYMENT_IMAGE }}
          CR_PAT: ${{ secrets.CR_PAT }}
    needs: [pre-env, pre-application, pre-ingress]
