name: Node.js CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: hmanzur/actions-set-secret@v2.0.0
        with:
          name: 'LAST_IMAGE_DOCKER'
          value: ${GITHUB_SHA}
          repository: 'easytecs/test-eks-deployment'
          token: ${{ secrets.CR_PAT }}
          org: true
          visibility: 'all'
